"""HubSpot integration — CRM pipeline for the AI lead generation swarm."""
from .platform_hub import PlatformHub

class HubSpotIntegration(PlatformHub):
    """CRM operations for qualifying and converting leads."""

    def ingest_swarm_lead(
        self, email: str, firstname: str, segment: str, source_swarm: str = "Lead Generation Agent"
    ) -> dict:
        """Create a HubSpot contact from a lead generated by the swarm."""
        contact = self.hubspot_create_contact(
            email=email, firstname=firstname,
            lifecycle_stage="lead",
            source=f"lippytm AI Swarm — {source_swarm}",
        )
        # Also log to D1 for internal tracking
        if 'id' in contact:
            self.d1_query(
                "INSERT INTO leads (email, source, segment, status, hubspot_id) VALUES (?, ?, ?, 'new', ?)",
                [email, source_swarm, segment, str(contact['id'])]
            )
        return contact
